spring:
  application:
    name: backlog-api

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:backlogdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
